// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/biz-strategy/CompetitiveAnalysis.tsx": () => import("../components/mockups/biz-strategy/CompetitiveAnalysis.tsx"),
  "./components/mockups/biz-strategy/EcosystemDashboard.tsx": () => import("../components/mockups/biz-strategy/EcosystemDashboard.tsx"),
  "./components/mockups/biz-strategy/EnterpriseDashboard.tsx": () => import("../components/mockups/biz-strategy/EnterpriseDashboard.tsx"),
  "./components/mockups/biz-strategy/IndieDashboard.tsx": () => import("../components/mockups/biz-strategy/IndieDashboard.tsx"),
  "./components/mockups/biz-strategy/PLGDashboard.tsx": () => import("../components/mockups/biz-strategy/PLGDashboard.tsx"),
  "./components/mockups/saas-variants/ControlRoom.tsx": () => import("../components/mockups/saas-variants/ControlRoom.tsx"),
  "./components/mockups/saas-variants/ExecSummary.tsx": () => import("../components/mockups/saas-variants/ExecSummary.tsx"),
  "./components/mockups/saas-variants/LiveFeed.tsx": () => import("../components/mockups/saas-variants/LiveFeed.tsx"),
  "./components/mockups/saas-variants/TabbedWorkspace.tsx": () => import("../components/mockups/saas-variants/TabbedWorkspace.tsx")
};
